### ISSUE TITLE
undefined value

### ISSUE THREAD

**Issue by shahinyan11** [jaroslawkrol/vision-camera-realtime-object-detection#7]
Below you can see a part of my code where the call detectObjects(frame, frameProcessorConfig) always returns  undefined

![Screenshot 2023-08-21 at 16 10 35](https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/46921547/45cb9fe8-4b2c-4b41-a106-9724c560f7e2)

I also looked at the logs in Android Studio and found this

![Screenshot 2023-08-21 at 16 15 30](https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/46921547/ea7f4444-893a-403c-8e6e-eca95f02a854)

Is there someone, who familiar with this error and managed to use the package without mentioned error ?

**Comment by hirendudhat03** [comment]
@shahinyan11 your model include metadata?
because I have same issue because my model not including metadata.

**Comment by Noahkoole** [comment]
Have you been able to fix this issue?

**Comment by arpkirill** [comment]
> Have you been able to fix this issue?

no

**Comment by Noahkoole** [comment]
@arpkirill Your logs in android studio explains the issue. You have 2 different kinds of tflite models. 1 with metadata including labels and stuff and 1 without. you can only use the tflite with metadata. if you take an example model from tflite website it works fine. I assume it uses MLKit or something underneath because MLKit also only works with metadata.

**Comment by arpkirill** [comment]
> @arpkirill Your logs in android studio explains the issue. You have 2 different kinds of tflite models. 1 with metadata including labels and stuff and 1 without. you can only use the tflite with metadata. if you take an example model from tflite website it works fine. I assume it uses MLKit or something underneath because MLKit also only works with metadata.

Tell me a fully working tflite file so that I can test

**Comment by arpkirill** [comment]
> @arpkirill Your logs in android studio explains the issue. You have 2 different kinds of tflite models. 1 with metadata including labels and stuff and 1 without. you can only use the tflite with metadata. if you take an example model from tflite website it works fine. I assume it uses MLKit or something underneath because MLKit also only works with metadata.

https://github.com/arpkirill/test-camera-object-detector

this is my demo project, which has a problem, I will be glad to hear your comments

**Comment by jejolare** [comment]
I have the same issue, tried several models. Btw, @arpkirill, your repository is private, we can't open

**Comment by jejolare** [comment]
@Noahkoole , could you provide any example of fully working model please 🙏?

**Comment by arpkirill** [comment]
> У меня такая же проблема, пробовал несколько моделей. Кстати,@arpkirill, ваш репозиторий приватный, мы не можем открыть



> I have the same issue, tried several models. Btw, @arpkirill, your repository is private, we can't open

I made it public, the only thing is to manually give permission to the phone camera

**Comment by arpkirill** [comment]
> I have the same issue, tried several models. Btw, @arpkirill, your repository is private, we can't open

I made it public, the only thing is to manually give permission to the phone camera

**Comment by arpkirill** [comment]
> I have the same issue, tried several models. Btw, @arpkirill, your repository is private, we can't open 

do you have any idea how to run it?

**Comment by jejolare** [comment]
> [arpkirill](/arpkirill)

idk, I can't run even their example. I have same issue, and have no idea what to do. I don't think that developer will help us soon:
![image](https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/85789854/fc18bca1-d2d3-4b94-be1f-4b665fd4d7dc)

**Comment by jejolare** [comment]
or maybe someone could provide us with working tflite

**Comment by arpkirill** [comment]
> > [arpkirill](/arpkirill)
> 
> idk, I can't run even their example. I have same issue, and have no idea what to do. I don't think that developer will help us soon:
> ![image](https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/85789854/fc18bca1-d2d3-4b94-be1f-4b665fd4d7dc)

In the demo project, you need to update the dependencies in Gradle, I don't remember which ones exactly. Did you launch my project?

**Comment by jaroslawkrol** [comment]
@arpkirill @jejolare As @Noahkoole and @hirendudhat03 mentioned above your model has to contains metadata. Remember about it if you wants to create your own TFLite model. It's not my library's requirement, it's just a TensorFlow Lite Vision requirement used in the background. 

If you want to test your code with existing correct model, just use [TFHub](https://tfhub.dev/s) as I mentioned in docs. To do it: 

1. Go to [TFHub.dev](https://tfhub.dev/s)
2. In filters select `Problem domains > Images > Object Detection`
<img width="258" alt="image" src="https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/10097549/a3d16653-89a9-46e6-8b83-de57eca2431f"><br />
3. Find one of models matched to your preferences and contains metadata included f.e. [ssd_mobilenet_v1](https://tfhub.dev/tensorflow/tfjs-model/ssd_mobilenet_v1/1/default/1)
<img width="415" alt="image" src="https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/10097549/4c0f201e-bbb0-43f8-b91c-28f3ed85bc84"><br />
4. In section `Model formats` click on tab with (metadata) if there is more than one format
<img width="1537" alt="image" src="https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/10097549/69cf7a8b-37d5-45b8-8671-2a797e5d28bb"><br />
5. Download it! 

Sorry guys, for so late response but as I mentioned in one of the threads my current project and private life consumes me totally. I also have my doubts that it still makes sense to maintain the library, because the new version of Vision Camera is going to bring big changes and possibility to use TFLite models just by drag & drop. But I need to talk with Marc about it to be sure, what is the current direction of Vision Camera library. 

@arpkirill Please, test your code with this model: https://tfhub.dev/tensorflow/lite-model/ssd_mobilenet_v1/1/metadata/2 and let me know about results, to know i can close this ticket. If not, we will try to resolve it together.

**Comment by arpkirill** [comment]
> @arpkirill @jejolare As @Noahkoole and @hirendudhat03 mentioned above your model has to contains metadata. Remember about it if you wants to create your own TFLite model. It's not my library's requirement, it's just a TensorFlow Lite Vision requirement used in the background. 
> 
> If you want to test your code on existing correct one, just use [TFHub](https://tfhub.dev/s) as I mentioned in docs. To do it: 
> 
> 1. Go to [TFHub.dev](https://tfhub.dev/s)
> 2. In filters select `Problem domains > Images > Object Detection`
> <img width="258" alt="image" src="https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/10097549/a3d16653-89a9-46e6-8b83-de57eca2431f"><br />
> 3. Find one of models matched to your preferences and contains metadata included f.e. [ssd_mobilenet_v1](https://tfhub.dev/tensorflow/tfjs-model/ssd_mobilenet_v1/1/default/1)
> <img width="415" alt="image" src="https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/10097549/4c0f201e-bbb0-43f8-b91c-28f3ed85bc84"><br />
> 4. In section `Model formats` click on tab with (metadata) if there is more than one format
> <img width="1537" alt="image" src="https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/10097549/69cf7a8b-37d5-45b8-8671-2a797e5d28bb"><br />
> 5. Download it! 
> 
> Sorry guys, for so late response but as I mentioned in one of the threads my current project and private life consumes me totally. I also have my doubts that it still makes sense to maintain the library, because the new version of Vision Camera is going to bring big changes and possibility to use TFLite models just by drag & drop. But I need to talk with Marc about it to be sure, what is the current direction of Vision Camera library. 
> 
> @arpkirill Please, test your code with this model: https://tfhub.dev/tensorflow/lite-model/ssd_mobilenet_v1/1/metadata/2 and let me know about results, to know i can close this ticket. If not, we will try to resolve it together. 
> 

![IMG_20230829_015242_143.jpg](https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/44532033/70fb365c-6054-47c6-94ef-206baa95e36e)

![IMG_20230829_015245_828.jpg](https://github.com/jaroslawkrol/vision-camera-realtime-object-detection/assets/44532033/558f9e26-0ad8-4484-b24d-c1efb1989f3e)

Everything works fine with this model, thank you very much for your help! I saw version 3, it looks cool, but as I understand it, it is still in the beta version.

**Comment by jaroslawkrol** [comment]
@arpkirill Thanks for quick reply! BTW. the prettiest cat i've ever seen 🤣

**Comment by ElicaInc** [comment]
Super! Great tutorial!
